import { Manrope, Space_Grotesk } from "next/font/google";
import Navigation from "./_components/Navigation";
import "./globals.css";
import Footer from "./_components/Footer";

const fontHeading = Space_Grotesk({
  variable: "--font-heading",
  weight: "700",
  subsets: ["latin"],
});

const fontText = Manrope({
  variable: "--font-text",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${fontHeading.variable} ${fontText.className} bg-bg-primary text-text-primary`}
    >
      <body className="min-h-full flex flex-col">
        <Navigation />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
